"""DIMER inference package for the pinned ``Salesforce/blip-vqa-base`` checkpoint."""

from .pipeline import (
    ANLS_THRESHOLD,
    DECODING,
    DEFAULT_MAX_NEW_TOKENS,
    DEFAULT_WEIGHTS_DIR,
    IMAGE_SIZE,
    INPUT_SCHEMA,
    MAX_IMAGE_SIDE,
    MAX_NEW_TOKENS,
    MAX_QUESTION_CHARS,
    MIN_IMAGE_SIDE,
    MODEL_ID,
    MODEL_KEY,
    MODEL_LICENSE,
    MODEL_REVISION,
    VQA_ACCURACY_DIVISOR,
    BlipVQAPipeline,
    anls,
    evaluation_report,
    exact_match,
    normalize_answer,
    stage_missing_files,
    validate_inputs,
    verify_snapshot,
    vqa_accuracy,
)

__all__ = [
    "ANLS_THRESHOLD",
    "DECODING",
    "DEFAULT_MAX_NEW_TOKENS",
    "DEFAULT_WEIGHTS_DIR",
    "IMAGE_SIZE",
    "INPUT_SCHEMA",
    "MAX_IMAGE_SIDE",
    "MAX_NEW_TOKENS",
    "MAX_QUESTION_CHARS",
    "MIN_IMAGE_SIDE",
    "MODEL_ID",
    "MODEL_KEY",
    "MODEL_LICENSE",
    "MODEL_REVISION",
    "VQA_ACCURACY_DIVISOR",
    "BlipVQAPipeline",
    "anls",
    "evaluation_report",
    "exact_match",
    "normalize_answer",
    "stage_missing_files",
    "validate_inputs",
    "verify_snapshot",
    "vqa_accuracy",
]
